### ISSUE TITLE
Check compatibility with networkx community detection algorithms

### ISSUE THREAD

**Issue by kawadia** [kawadia/estrangement#12]
There was a GSoC project in 2011 to write community detection algos for networkx. Check its status and see if can use some of the utils and classes developed there:

https://bitbucket.org/bedwards/networkx-community

**Comment by dabideen** [comment]
This isn't yet a part of networkx, and hasnt been updated in almost a year. It might be dead.
There are a couple similar functions: they are agglomarative.py which does something similar to agglomerate.best_partition but wont be able to handle delta as a parameter, they also have a modularity function, but it take a list of sets as the community, rather than a dictionary....and this is one of the big difference throughout their code.

Other python community detection code:
http://igraph.wikidot.com/community-detection-in-python
http://projects.skewed.de/graph-tool/doc/community.html
http://webhome.csc.uvic.ca/~jahan/codes/cmty.html

**Comment by kawadia** [comment]
ok. lets not integrate with this now.

On Wed, Jul 11, 2012 at 10:54 AM, dabideen <
reply@reply.github.com
